In [2]:
from langchain_groq import ChatGroq

In [3]:
!pip install langchain
!pip install langchain_groq
!pip install -r requirements.txt
!pip install chromadb
!pip install langchain_community

Requirement already satisfied: langchain in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (1.3.2)
Requirement already satisfied: langchain-core<2.0.0,>=1.4.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from langchain) (1.4.0)
Requirement already satisfied: langgraph<1.3.0,>=1.2.2 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from langchain) (1.2.2)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from langchain) (2.13.4)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain) (1.33)
Requirement already satisfied: langchain-protocol>=0.0.14 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain) (0.0.15)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain) (0.8.6)
Requirement already satisfied: packaging>=23.2.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain) (25.0)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain) (9.1.4)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain) (4.15.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.4.0->langchain) (3.0.0)
Requirement already satisfied: langgraph-checkpoint<5.0.0,>=4.1.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from langgraph<1.3.0,>=1.2.2->langchain) (4.1.1)
Requirement already satisfied: langgraph-prebuilt<1.2.0,>=1.1.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from langgraph<1.3.0,>=1.2.2->langchain) (1.1.0)
Requirement already satisfied: langgraph-sdk<0.4.0,>=0.3.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from langgraph<1.3.0,>=1.2.2->langchain) (0.3.15)
Requirement already satisfied: xxhash>=3.5.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from langgraph<1.3.0,>=1.2.2->langchain) (3.7.0)
Requirement already satisfied: ormsgpack>=1.12.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from langgraph-checkpoint<5.0.0,>=4.1.0->langgraph<1.3.0,>=1.2.2->langchain) (1.12.2)
Requirement already satisfied: httpx>=0.25.2 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.3.0,>=1.2.2->langchain) (0.28.1)
Requirement already satisfied: orjson>=3.11.5 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.3.0,>=1.2.2->langchain) (3.11.9)
Requirement already satisfied: requests-toolbelt>=1.0.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.0->langchain) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.0->langchain) (2.32.5)
Requirement already satisfied: websockets>=15.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.0->langchain) (16.0)
Requirement already satisfied: zstandard>=0.23.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.0->langchain) (0.25.0)
Requirement already satisfied: anyio in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.3.0,>=1.2.2->langchain) (4.12.0)
Requirement already satisfied: certifi in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.3.0,>=1.2.2->langchain) (2025.11.12)
Requirement already satisfied: httpcore==1.* in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.3.0,>=1.2.2->langchain) (1.0.9)
Requirement already satisfied: idna in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.3.0,>=1.2.2->langchain) (3.11)
Requirement already satisfied: h11>=0.16 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from httpcore==1.*->httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.3.0,>=1.2.2->langchain) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.0->langchain) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.0->langchain) (2.6.2)

[notice] A new release of pip is available: 25.3 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: langchain_groq in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (1.1.2)
Requirement already satisfied: groq<1.0.0,>=0.30.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from langchain_groq) (0.37.1)
Requirement already satisfied: langchain-core<2.0.0,>=1.2.8 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from langchain_groq) (1.4.0)
Requirement already satisfied: anyio<5,>=3.5.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from groq<1.0.0,>=0.30.0->langchain_groq) (4.12.0)
Requirement already satisfied: distro<2,>=1.7.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from groq<1.0.0,>=0.30.0->langchain_groq) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from groq<1.0.0,>=0.30.0->langchain_groq) (0.28.1)
Requirement already satisfied: pydantic<3,>=1.9.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from groq<1.0.0,>=0.30.0->langchain_groq) (2.13.4)
Requirement already satisfied: sniffio in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from groq<1.0.0,>=0.30.0->langchain_groq) (1.3.1)
Requirement already satisfied: typing-extensions<5,>=4.10 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from groq<1.0.0,>=0.30.0->langchain_groq) (4.15.0)
Requirement already satisfied: idna>=2.8 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from anyio<5,>=3.5.0->groq<1.0.0,>=0.30.0->langchain_groq) (3.11)
Requirement already satisfied: certifi in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from httpx<1,>=0.23.0->groq<1.0.0,>=0.30.0->langchain_groq) (2025.11.12)
Requirement already satisfied: httpcore==1.* in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from httpx<1,>=0.23.0->groq<1.0.0,>=0.30.0->langchain_groq) (1.0.9)
Requirement already satisfied: h11>=0.16 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->groq<1.0.0,>=0.30.0->langchain_groq) (0.16.0)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from langchain-core<2.0.0,>=1.2.8->langchain_groq) (1.33)
Requirement already satisfied: langchain-protocol>=0.0.14 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from langchain-core<2.0.0,>=1.2.8->langchain_groq) (0.0.15)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from langchain-core<2.0.0,>=1.2.8->langchain_groq) (0.8.6)
Requirement already satisfied: packaging>=23.2.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from langchain-core<2.0.0,>=1.2.8->langchain_groq) (25.0)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from langchain-core<2.0.0,>=1.2.8->langchain_groq) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from langchain-core<2.0.0,>=1.2.8->langchain_groq) (9.1.4)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from langchain-core<2.0.0,>=1.2.8->langchain_groq) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.2.8->langchain_groq) (3.0.0)
Requirement already satisfied: orjson>=3.9.14 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.8->langchain_groq) (3.11.9)
Requirement already satisfied: requests-toolbelt>=1.0.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.8->langchain_groq) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.8->langchain_groq) (2.32.5)
Requirement already satisfied: websockets>=15.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.8->langchain_groq) (16.0)
Requirement already satisfied: xxhash>=3.0.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.8->langchain_groq) (3.7.0)
Requirement already satisfied: zstandard>=0.23.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.8->langchain_groq) (0.25.0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from pydantic<3,>=1.9.0->groq<1.0.0,>=0.30.0->langchain_groq) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from pydantic<3,>=1.9.0->groq<1.0.0,>=0.30.0->langchain_groq) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from pydantic<3,>=1.9.0->groq<1.0.0,>=0.30.0->langchain_groq) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.8->langchain_groq) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.8->langchain_groq) (2.6.2)

[notice] A new release of pip is available: 25.3 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

[notice] A new release of pip is available: 25.3 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

Requirement already satisfied: chromadb in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (1.5.9)
Requirement already satisfied: build>=1.0.3 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from chromadb) (1.5.0)
Requirement already satisfied: pydantic>=2.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from chromadb) (2.13.4)
Requirement already satisfied: pydantic-settings>=2.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from chromadb) (2.14.1)
Requirement already satisfied: pybase64>=1.4.1 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from chromadb) (1.4.3)
Requirement already satisfied: uvicorn>=0.18.3 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.48.0)
Requirement already satisfied: numpy>=1.22.5 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from chromadb) (2.4.0)
Requirement already satisfied: typing-extensions>=4.5.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from chromadb) (4.15.0)
Requirement already satisfied: onnxruntime>=1.14.1 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from chromadb) (1.26.0)
Requirement already satisfied: opentelemetry-api>=1.2.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from chromadb) (1.42.1)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-grpc>=1.2.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from chromadb) (1.42.1)
Requirement already satisfied: opentelemetry-sdk>=1.2.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from chromadb) (1.42.1)
Requirement already satisfied: tokenizers>=0.13.2 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from chromadb) (0.23.1)
Requirement already satisfied: pypika>=0.48.9 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from chromadb) (0.51.1)
Requirement already satisfied: tqdm>=4.65.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from chromadb) (4.67.3)
Requirement already satisfied: overrides>=7.3.1 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from chromadb) (7.7.0)
Requirement already satisfied: importlib-resources in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from chromadb) (7.1.0)
Requirement already satisfied: grpcio>=1.58.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from chromadb) (1.80.0)
Requirement already satisfied: bcrypt>=4.0.1 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from chromadb) (5.0.0)
Requirement already satisfied: typer>=0.9.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from chromadb) (0.25.1)
Requirement already satisfied: kubernetes>=28.1.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from chromadb) (36.0.1)
Requirement already satisfied: tenacity>=8.2.3 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from chromadb) (9.1.4)
Requirement already satisfied: pyyaml>=6.0.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from chromadb) (6.0.3)
Requirement already satisfied: mmh3>=4.0.1 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from chromadb) (5.2.1)
Requirement already satisfied: orjson>=3.9.12 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from chromadb) (3.11.9)
Requirement already satisfied: httpx>=0.27.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from chromadb) (0.28.1)
Requirement already satisfied: rich>=10.11.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from chromadb) (15.0.0)
Requirement already satisfied: jsonschema>=4.19.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from chromadb) (4.25.1)
Requirement already satisfied: packaging>=24.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from build>=1.0.3->chromadb) (25.0)
Requirement already satisfied: pyproject_hooks in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from build>=1.0.3->chromadb) (1.2.0)
Requirement already satisfied: colorama in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from build>=1.0.3->chromadb) (0.4.6)
Requirement already satisfied: anyio in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from httpx>=0.27.0->chromadb) (4.12.0)
Requirement already satisfied: certifi in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from httpx>=0.27.0->chromadb) (2025.11.12)
Requirement already satisfied: httpcore==1.* in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from httpx>=0.27.0->chromadb) (1.0.9)
Requirement already satisfied: idna in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from httpx>=0.27.0->chromadb) (3.11)
Requirement already satisfied: h11>=0.16 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from httpcore==1.*->httpx>=0.27.0->chromadb) (0.16.0)
Requirement already satisfied: attrs>=22.2.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from jsonschema>=4.19.0->chromadb) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from jsonschema>=4.19.0->chromadb) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from jsonschema>=4.19.0->chromadb) (0.37.0)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from jsonschema>=4.19.0->chromadb) (0.30.0)
Requirement already satisfied: six>=1.9.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from kubernetes>=28.1.0->chromadb) (1.17.0)
Requirement already satisfied: python-dateutil>=2.5.3 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from kubernetes>=28.1.0->chromadb) (2.9.0.post0)
Requirement already satisfied: websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from kubernetes>=28.1.0->chromadb) (1.9.0)
Requirement already satisfied: requests in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from kubernetes>=28.1.0->chromadb) (2.32.5)
Requirement already satisfied: requests-oauthlib in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from kubernetes>=28.1.0->chromadb) (2.0.0)
Requirement already satisfied: urllib3!=2.6.0,>=1.24.2 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from kubernetes>=28.1.0->chromadb) (2.6.2)
Requirement already satisfied: durationpy>=0.7 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from kubernetes>=28.1.0->chromadb) (0.10)
Requirement already satisfied: aiohttp<4.0.0,>=3.13.5 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from kubernetes>=28.1.0->chromadb) (3.13.5)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from aiohttp<4.0.0,>=3.13.5->kubernetes>=28.1.0->chromadb) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from aiohttp<4.0.0,>=3.13.5->kubernetes>=28.1.0->chromadb) (1.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from aiohttp<4.0.0,>=3.13.5->kubernetes>=28.1.0->chromadb) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from aiohttp<4.0.0,>=3.13.5->kubernetes>=28.1.0->chromadb) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from aiohttp<4.0.0,>=3.13.5->kubernetes>=28.1.0->chromadb) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from aiohttp<4.0.0,>=3.13.5->kubernetes>=28.1.0->chromadb) (1.24.2)
Requirement already satisfied: flatbuffers in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from onnxruntime>=1.14.1->chromadb) (25.12.19)
Requirement already satisfied: protobuf in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from onnxruntime>=1.14.1->chromadb) (6.33.6)
Requirement already satisfied: googleapis-common-protos~=1.57 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.75.0)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-common==1.42.1 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.42.1)
Requirement already satisfied: opentelemetry-proto==1.42.1 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.42.1)
Requirement already satisfied: opentelemetry-semantic-conventions==0.63b1 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from opentelemetry-sdk>=1.2.0->chromadb) (0.63b1)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from pydantic>=2.0->chromadb) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from pydantic>=2.0->chromadb) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from pydantic>=2.0->chromadb) (0.4.2)
Requirement already satisfied: python-dotenv>=0.21.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from pydantic-settings>=2.0->chromadb) (1.2.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from rich>=10.11.0->chromadb) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from rich>=10.11.0->chromadb) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->chromadb) (0.1.2)
Requirement already satisfied: huggingface-hub<2.0,>=0.16.4 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from tokenizers>=0.13.2->chromadb) (1.16.4)
Requirement already satisfied: click>=8.4.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.13.2->chromadb) (8.4.1)
Requirement already satisfied: filelock>=3.10.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.13.2->chromadb) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.13.2->chromadb) (2026.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.13.2->chromadb) (1.5.0)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from typer>=0.9.0->chromadb) (1.5.4)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from typer>=0.9.0->chromadb) (0.0.4)
Requirement already satisfied: httptools>=0.6.3 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.8.0)
Requirement already satisfied: watchfiles>=0.20 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from uvicorn[standard]>=0.18.3->chromadb) (1.2.0)
Requirement already satisfied: websockets>=10.4 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from uvicorn[standard]>=0.18.3->chromadb) (16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from requests->kubernetes>=28.1.0->chromadb) (3.4.4)
Requirement already satisfied: oauthlib>=3.0.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from requests-oauthlib->kubernetes>=28.1.0->chromadb) (3.3.1)

[notice] A new release of pip is available: 25.3 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: langchain_community in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (0.4.2)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from langchain_community) (3.13.5)
Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from langchain_community) (0.4.3)
Requirement already satisfied: langchain-classic<2.0.0,>=1.0.7 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from langchain_community) (1.0.7)
Requirement already satisfied: langchain-core<2.0.0,>=1.4.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from langchain_community) (1.4.0)
Requirement already satisfied: langsmith<1.0.0,>=0.1.125 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from langchain_community) (0.8.6)
Requirement already satisfied: numpy>=2.1.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from langchain_community) (2.4.0)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.10.1 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from langchain_community) (2.14.1)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from langchain_community) (6.0.3)
Requirement already satisfied: requests<3.0.0,>=2.32.5 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from langchain_community) (2.32.5)
Requirement already satisfied: sqlalchemy<3.0.0,>=1.4.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from langchain_community) (2.0.50)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from langchain_community) (9.1.4)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (1.24.2)
Requirement already satisfied: langchain-text-splitters<2.0.0,>=1.1.2 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from langchain-classic<2.0.0,>=1.0.7->langchain_community) (1.1.2)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from langchain-classic<2.0.0,>=1.0.7->langchain_community) (2.13.4)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain_community) (1.33)
Requirement already satisfied: langchain-protocol>=0.0.14 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain_community) (0.0.15)
Requirement already satisfied: packaging>=23.2.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain_community) (25.0)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain_community) (4.15.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain_community) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.4.0->langchain_community) (3.0.0)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from langsmith<1.0.0,>=0.1.125->langchain_community) (0.28.1)
Requirement already satisfied: orjson>=3.9.14 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from langsmith<1.0.0,>=0.1.125->langchain_community) (3.11.9)
Requirement already satisfied: requests-toolbelt>=1.0.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from langsmith<1.0.0,>=0.1.125->langchain_community) (1.0.0)
Requirement already satisfied: websockets>=15.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from langsmith<1.0.0,>=0.1.125->langchain_community) (16.0)
Requirement already satisfied: xxhash>=3.0.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from langsmith<1.0.0,>=0.1.125->langchain_community) (3.7.0)
Requirement already satisfied: zstandard>=0.23.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from langsmith<1.0.0,>=0.1.125->langchain_community) (0.25.0)
Requirement already satisfied: anyio in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain_community) (4.12.0)
Requirement already satisfied: certifi in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain_community) (2025.11.12)
Requirement already satisfied: httpcore==1.* in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain_community) (1.0.9)
Requirement already satisfied: idna in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain_community) (3.11)
Requirement already satisfied: h11>=0.16 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain_community) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from pydantic<3.0.0,>=2.7.4->langchain-classic<2.0.0,>=1.0.7->langchain_community) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from pydantic<3.0.0,>=2.7.4->langchain-classic<2.0.0,>=1.0.7->langchain_community) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from pydantic<3.0.0,>=2.7.4->langchain-classic<2.0.0,>=1.0.7->langchain_community) (0.4.2)
Requirement already satisfied: python-dotenv>=0.21.0 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain_community) (1.2.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from requests<3.0.0,>=2.32.5->langchain_community) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from requests<3.0.0,>=2.32.5->langchain_community) (2.6.2)
Requirement already satisfied: greenlet>=1 in c:\users\hp user\appdata\local\programs\python\python314\lib\site-packages (from sqlalchemy<3.0.0,>=1.4.0->langchain_community) (3.5.1)

[notice] A new release of pip is available: 25.3 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
llm = ChatGroq(
    temperature=0, 
    groq_api_key='GROQ_API_KEY', 
    model_name="llama-3.3-70b-versatile"
)
response = llm.invoke("The first person to land on moon was ...")
print(response.content)

The first person to land on the moon was Neil Armstrong. He stepped out of the lunar module Eagle and onto the moon's surface on July 20, 1969, during the Apollo 11 mission. Armstrong famously declared, "That's one small step for man, one giant leap for mankind," as he became the first human to set foot on the moon.

In [5]:
import os
os.environ["USER_AGENT"]="myapp/1.0"

In [6]:
from langchain_community.document_loaders import WebBaseLoader
loader = WebBaseLoader("https://jobs.nike.com/job/R-33460")
page_data = loader.load().pop().page_content
print(page_data)

C:\Users\HP USER\AppData\Local\Temp\ipykernel_11576\4086205905.py:1: DeprecationWarning: `langchain-community` is being sunset and is no longer actively maintained. See https://github.com/langchain-ai/langchain-community/issues/674 for details and migration guidance toward standalone integration packages.
  from langchain_community.document_loaders import WebBaseLoader

Nike Careers











































Skip to main content
Open Virtual Assistant










Home


Career Areas


Total Rewards


Life@Nike


Purpose










Language





Select a Language

  Deutsch
  English
  Español (España)
  Español (América Latina)
  Français
  Italiano
  Nederlands
  Polski
  Tiếng Việt
  Türkçe
  简体中文
  繁體中文
  עִברִית
  한국어
  日本語








Careers


















Close Menu







Careers






Chat






                                Home




                                Career Areas




                                Total Rewards




                                Life@Nike




                                Purpose











Jordan Careers







Converse Careers










Language











Menu



Return to Previous Menu



Select a Language

  Deutsch
  English
  Español (España)
  Español (América Latina)
  Français
  Italiano
  Nederlands
  Polski
  Tiếng Việt
  Türkçe
  简体中文
  繁體中文
  עִברִית
  한국어
  日本語












                Your browser doesn't support HTML5 video tag.










Play Full Video



WHAT MOVES YOUMOVES OUR WORLD







Pause Video



Play Video






Play 'How We Do It' video




Play 'Victory Mode' video'




Play 'Craft the Future' video











Be In the Know










Retail at NIKE, Inc.
Learn More










The Nike Internship Experience
Learn More










AI/ML Roles for Innovators
Learn More










Peek Into Our World
Learn More










NikeUNITED's Commitment
Learn More













IF YOU HAVE A BODY, YOU ARE AN ATHLETE.*



These words drive who we are and what we believe in – a better future for ourselves, our communities and our athletes. We strive to bring inspiration and innovation to every athlete in the world, including our teammates.








More Than Love of the Brand
WHAT MOVES US







Serve Athletes



We believe in the power of sport. Taking ownership of our shared responsibility to action the voice of all athletes, we push ourselves and each other, turning ambition into achievement.













Expand Serve Athletes Section







Create the Future of Sport



We understand every idea must meet a need and move people closer to their goals. That's why we're not afraid to fail - because innovation depends on risk.













Expand Create the Future of Sport section







Be On the Offense Always



Agility is our edge. We put the consumer first by setting the pace, acting decisively and driving change to meet their
                                            needs.













Expand Be On the Offense Always section







Do the Right Thing



We value our unique opportunity to put ethics into action on the journey to level the playing field for all. This requires accountability, meaning we consistently make calls and own the results.













Expand Do the Right Thing section







Win as a Team



We are strong together. Creating an environment where deep connections champion collaboration, it is expected that each player not only contributes to our collective wins but celebrates them.













Expand Win as a Team section












Go to Previous Slide





Go to Next Slide












Reinforcing Our Position
CULTURE IN ACTION
There is a sense of pride that comes from representing an iconic brand and shaping its future. Here, we treat
                            every day
                            as a new opportunity to push boundaries, ask tough questions and share whole-hearted convictions. We are a
                            team – united
                            by the belief that anything is possible.
Learn More About Culture







Elevating Your Well-Being
FROM THE INSIDE OUT
Rest and recovery are critical for you to be able to deliver at peak performance. You can count on us to walk
                        the talk,
                        providing resources and time that help keep life balanced and yourself fueled for any challenge. Compassion
                        and
                        flexibility enhance the supportive nature of our community.
Learn More About Benefits







Lacing Up for the Greater Good
PURPOSE AT PLAY
Moving the world forward through sport is no small feat. Together, we take steps to drive change by putting
                            social
                            impact and planet protection first. This shared passion for doing what's right fuels the NIKE, Inc. legacy
                            and drives us
                            forward.
Learn
                            More






One Team. Iconic Brands.
BEYOND THE SWOOSH






Converse
Bringing together those independent enough not to follow, we are catalyzing the collective power of people who see their differences as strengths. Converse is a creative team channeling ambition, expertise, and self-expression to drive innovation.
Learn More About Converse





Jordan
Extending beyond sports into culture and fashion, Jordan Brand is bound by a commitment to serve a community representative of Michael himself. Those who make up this team thrive in an entrepreneurial environment, where creative problem-solving is leveraged to drive innovation.






Search Jordan Careers






Explore Careers









Search Retail Careers










Search Distribution Careers










Search Manufacturing Careers










Search Corporate Careers










Search Open Internships














SEARCH CAREERS





Close Modal







                                    Apply Filters


                                    Clear Filters






All
                                                Careers



Retail


Distribution


Manufacturing


Corporate


Internships






Keyword SearchLocation SearchUse your locationUse your locationSearch


Filters




Filter ResultsCareer AreasAdvanced Innovation2Business Operations7Communications4Data2Design33Facilities & Real Estate3Finance & Accounting7General Counsel1Human Resources7Position TypeFull Time624Part Time225Is RemoteNo895Yes4BrandCONVERSE85JORDAN15NIKE799cf_employee_typeFixed Term Contract (Fixed Term)191Intern (Fixed Term)11Regular511Seasonal (Fixed Term) (Seasonal)168Temp Casual (Fixed Term)17Temp Trainee (Trainee)1cf_job_categoryCorporate214Distribution4Manufacturing4Retail677Clear Filter






 Join The Talent Community





Contract Jobs - USA Only*












Edit Filters









Kaufmann/-frau im Einzelhandel (Ausbildung) - 37.5H - Metzingen (w/m/d)R-81196Job LocationMetzingen, Baden-Wurttemberg, GermanyRetail StoresView JobNike Operational Teamleiter (Lead) (w/m/d) – 38.5 (h) – NFS ParndorfR-82525Job LocationParndorf, Burgenland, AustriaRetail StoresView JobCoach Stockroom I Gerente de Almacén - NFS MX TijuanaR-83888Job LocationTijuana, Baja California, MexicoRetail StoresView JobAthlete IIIR-84211Job LocationHefei, Anhui, ChinaRetail StoresView JobRetail Associate, PT - Nike Dania Pointe (14-29 hours/week)R-81706Job LocationDania Beach, Florida, United StatesRetail StoresView JobAthlete IIR-56644Job LocationGuangzhou, Guangdong, ChinaRetail StoresView JobSenior, Running & ACG Footwear Product Testing AnalystR-84388Job LocationBeaverton, Oregon, United StatesProduct Creation, Development & ManagementView JobDepartment Manager - Full Time - Nike PireosR-82651Job LocationAthens, Achaia, GreeceRetail StoresView JobRetail Associate, SEAS - Nike Pismo Beach (0-40 hours/week)R-783358Job LocationPismo Beach, California, United StatesRetail StoresView JobSenior Materials Designer CTM - ConverseR-80918Job LocationShanghai, Shanghai, ChinaProduct Creation, Development & ManagementView Job
Go to first pageGo to previous page12345678910Go to next pageGo to last page1020











Close

























Home


About Us


Contact


Talent Community


Terms












































                    Nike Applicant Privacy Policy






We offer a number of accommodations to complete our interview process including screen readers, sign language interpreters,
                accessible and single location for in-person interviews, closed captioning, and other reasonable modifications as
                needed.


If you discover, as you navigate our application process, that you need assistance or an accommodation due to a
                disability, please contact us at +1 503-671-4156 and include your full name, best way to reach you, and the
                accommodation you request to assist with the application process.
For more information, please refer to Equal Employment
                        Opportunity is The Law.



©  Nike, Inc. All Rights Reserved













Careers








Chat
Chat with our AI Assistant

In [7]:
from langchain_core.prompts import PromptTemplate

prompt_extract = PromptTemplate.from_template(
        """
        ### SCRAPED TEXT FROM WEBSITE:
        {page_data}
        ### INSTRUCTION:
        The scraped text is from the career's page of a website.
        Your job is to extract the job postings and return them in JSON format containing the 
        following keys: `role`, `experience`, `skills` and `description`.
        Only return the valid JSON.
        ### VALID JSON (NO PREAMBLE):    
        """
)

chain_extract = prompt_extract | llm 
res = chain_extract.invoke(input={'page_data':page_data})
type(res.content)

str

In [25]:

from langchain_core.output_parsers import JsonOutputParser

json_parser = JsonOutputParser()
json_res = json_parser.parse(res.content)
json_res=json_res[0]
json_res
job=json_res

In [26]:
type(json_res)

dict

In [27]:
import pandas as pd

df = pd.read_csv(r"D:\Downloads_In_D\my_portfolio.csv")
df

,Techstack,Links
0,"React, Node.js, MongoDB",https://example.com/react-portfolio
1,"Angular,.NET, SQL Server",https://example.com/angular-portfolio
2,"Vue.js, Ruby on Rails, PostgreSQL",https://example.com/vue-portfolio
3,"Python, Django, MySQL",https://example.com/python-portfolio
4,"Java, Spring Boot, Oracle",https://example.com/java-portfolio
5,"Flutter, Firebase, GraphQL",https://example.com/flutter-portfolio
6,"WordPress, PHP, MySQL",https://example.com/wordpress-portfolio
7,"Magento, PHP, MySQL",https://example.com/magento-portfolio
8,"React Native, Node.js, MongoDB",https://example.com/react-native-portfolio
9,"iOS, Swift, Core Data",https://example.com/ios-portfolio
10,"Android, Java, Room Persistence",https://example.com/android-portfolio
11,"Kotlin, Android, Firebase",https://example.com/kotlin-android-portfolio
12,"Android TV, Kotlin, Android NDK",https://example.com/android-tv-portfolio
13,"iOS, Swift, ARKit",https://example.com/ios-ar-portfolio
14,"Cross-platform, Xamarin, Azure",https://example.com/xamarin-portfolio
15,"Backend, Kotlin, Spring Boot",https://example.com/kotlin-backend-portfolio
16,"Frontend, TypeScript, Angular",https://example.com/typescript-frontend-portfolio
17,"Full-stack, JavaScript, Express.js",https://example.com/full-stack-js-portfolio
18,"Machine Learning, Python, TensorFlow",https://example.com/ml-python-portfolio
19,"DevOps, Jenkins, Docker",https://example.com/devops-portfolio

In [28]:
df.head()

                           Techstack                                  Links
0            React, Node.js, MongoDB    https://example.com/react-portfolio
1           Angular,.NET, SQL Server  https://example.com/angular-portfolio
2  Vue.js, Ruby on Rails, PostgreSQL      https://example.com/vue-portfolio
3              Python, Django, MySQL   https://example.com/python-portfolio
4          Java, Spring Boot, Oracle     https://example.com/java-portfolio

In [29]:
import uuid
import chromadb

client = chromadb.PersistentClient('vectorstore')
collection = client.get_or_create_collection(name="portfolio")

if not collection.count():
    for _, row in df.iterrows():
        collection.add(documents=row["Techstack"],
                       metadatas={"links": row["Links"]},
                       ids=[str(uuid.uuid4())])

In [30]:
links = collection.query(query_texts=job['skills'], n_results=2).get('metadatas', [])
links

[[{'links': 'https://example.com/magento-portfolio'},
  {'links': 'https://example.com/wordpress-portfolio'}]]

In [31]:
print(type(job))

<class 'dict'>

In [32]:
job

{'role': 'Kaufmann/-frau im Einzelhandel (Ausbildung)',
 'experience': 'Entry-level',
 'skills': 'Retail, Sales',
 'description': '37.5H - Metzingen (w/m/d)'}

In [33]:
job = json_res
job['skills']

'Retail, Sales'

In [34]:
prompt_email = PromptTemplate.from_template(
        """
        ### JOB DESCRIPTION:
        {job_description}
        
        ### INSTRUCTION:
        You are Mohan, a business development executive at AtliQ. AtliQ is an AI & Software Consulting company dedicated to facilitating
        the seamless integration of business processes through automated tools. 
        Over our experience, we have empowered numerous enterprises with tailored solutions, fostering scalability, 
        process optimization, cost reduction, and heightened overall efficiency. 
        Your job is to write a cold email to the client regarding the job mentioned above describing the capability of AtliQ 
        in fulfilling their needs.
        Also add the most relevant ones from the following links to showcase Atliq's portfolio: {link_list}
        Remember you are Mohan, BDE at AtliQ. 
        Do not provide a preamble.
        ### EMAIL (NO PREAMBLE):
        
        """
        )

chain_email = prompt_email | llm
res = chain_email.invoke({"job_description": str(job), "link_list": links})
print(res.content)

Subject: Enhance Your Retail Operations with AtliQ's Expertise

Dear Hiring Manager,

I came across the job posting for a Kaufmann/-frau im Einzelhandel (Ausbildung) at your esteemed organization, and I am excited to introduce AtliQ, a leading AI & Software Consulting company. As a business development executive, I believe our expertise can significantly enhance your retail operations and support the growth of your sales team.

At AtliQ, we specialize in developing tailored solutions that cater to the unique needs of businesses like yours. Our team of experts can help you streamline your retail processes, optimize sales, and reduce costs. With our automated tools, you can focus on what matters most - providing exceptional customer experiences and driving business growth.

Our portfolio showcases our capabilities in delivering high-quality solutions for various industries, including retail. I would like to draw your attention to our Magento portfolio (https://example.com/magento-portfolio), which demonstrates our expertise in creating seamless e-commerce experiences. Additionally, our WordPress portfolio (https://example.com/wordpress-portfolio) highlights our ability to craft engaging online platforms that drive sales and customer engagement.

By partnering with AtliQ, you can leverage our technical expertise to:

* Develop customized retail solutions that meet your specific needs
* Implement efficient sales processes that enhance customer satisfaction
* Analyze sales data to inform business decisions and optimize operations

I would be delighted to discuss how AtliQ can support your business goals and provide a tailored solution for your retail operations. Please do not hesitate to contact me to schedule a call.

Best regards,

Mohan
Business Development Executive
AtliQ